### ISSUE TITLE
Warning message: The plyr::rename operation has created duplicates for the following name(s): (`Cluster`) - when trying to do merge_results for cluster pathways

### ISSUE THREAD

**Issue by veldahan** [GuangchuangYu/frog_tree#2]
Hi! i have done 2 cluster comparisons between 3 groups of patients. Want to merge the results for these 2 comparisons, but i get this warning message: Warning message: The plyr::rename operation has created duplicates for the following name(s): (`Cluster`) 

Code: 
merge_result(list(A_up= my_reacprevscontrol %>% filter(direction == "Up"), A_down= my_reacprevscontrol %>% filter(direction == "Down"), B_up= my_reacpostvspre %>% filter(direction == "Up"), B_down= my_reacpostvspre %>% filter(direction == "Down"))) %>% dotplot(., showCategory=200, title = "Reactome region-specific pathway enrichments") + facet_grid(~direction)

Any way to avoid this error message? Thank you!
V

**Comment by GuangchuangYu** [comment]
not related to this repo.
